In [1]:
import pandas as pd
import numpy as np

In [2]:
df1SE =  pd.DataFrame({ 'StudentID': [1,3,5,7,9],
                       'ScoreSE' : [34,11,55,82,90]})

df2SE =  pd.DataFrame({'StudentID': [2,4,6,8,10],
                       'ScoreSE': [50,22,56,18,99]})

df1ML =  pd.DataFrame({ 'StudentID': [1,3,5,7,9],
                       'ScoreML' : [70,99,17,58,89]})

df2ML =  pd.DataFrame({'StudentID': [2, 4, 6, 8, 10],
                       'ScoreML': [93, 44, 78, 97, 87]})

In [3]:
#Consolidate the Course Data

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = pd.concat([dfML, dfSE], axis=1)
df

   StudentID  ScoreML  StudentID  ScoreSE
0          1       70          1       34
1          3       99          3       11
2          5       17          5       55
3          7       58          7       82
4          9       89          9       90
5          2       93          2       50
6          4       44          4       22
7          6       78          6       56
8          8       97          8       18
9         10       87         10       99

In [4]:
# Calculate Totals with an Outer Join

df_total = dfSE.merge(dfML, on='StudentID', how='outer')
total_count = len(df_total)
total_count

10

In [5]:
# Outer Join

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='outer')
df

   StudentID  ScoreSE  ScoreML
0          1       34       70
1          3       11       99
2          5       55       17
3          7       82       58
4          9       90       89
5          2       50       93
6          4       22       44
7          6       56       78
8          8       18       97
9         10       99       87

In [6]:
# Left Join

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='left')
df

   StudentID  ScoreSE  ScoreML
0          1       34       70
1          3       11       99
2          5       55       17
3          7       82       58
4          9       90       89
5          2       50       93
6          4       22       44
7          6       56       78
8          8       18       97
9         10       99       87

In [7]:
# Right Join

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='right')
df

   StudentID  ScoreSE  ScoreML
0          1       34       70
1          3       11       99
2          5       55       17
3          7       82       58
4          9       90       89
5          2       50       93
6          4       22       44
7          6       56       78
8          8       18       97
9         10       99       87

**Reshaping with Hierarchical Indexing**

In [8]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Delhi', 'Bangalore', 'Mumbai', 'Chennai', 'Panaji'])
dframe1

          Delhi  Bangalore  Mumbai  Chennai  Panaji
Rainfall      0          1       2        3       4
Humidity      5          6       7        8       9
Wind         10         11      12       13      14

In [9]:
stacked = dframe1.stack()
stacked

Rainfall  Delhi         0
          Bangalore     1
          Mumbai        2
          Chennai       3
          Panaji        4
Humidity  Delhi         5
          Bangalore     6
          Mumbai        7
          Chennai       8
          Panaji        9
Wind      Delhi        10
          Bangalore    11
          Mumbai       12
          Chennai      13
          Panaji       14
dtype: int32

In [10]:
stacked.unstack()

          Delhi  Bangalore  Mumbai  Chennai  Panaji
Rainfall      0          1       2        3       4
Humidity      5          6       7        8       9
Wind         10         11      12       13      14

In [11]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
frame2.unstack()

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN